CAMINHO_JOGOS = "games.dat"
CAMINHO_INDICE_GENEROS = "genero.ind"
CAMINHO_INDICE_PUBLICADORAS = "publicadora.ind"
CAMINHO_LISTA_INVERTIDA = "listaInvertida.lst"
LISTA_INDICES_SECUNDARIOS = [CAMINHO_INDICE_GENEROS, CAMINHO_INDICE_PUBLICADORAS]